server:
  port: 4000

spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:db.sqlite?date_class=TEXT


  jpa:
    database-platform: com.example.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: false